name: CI Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in root
        run: Get-ChildItem -Recurse

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: todo-angular

      - name: Run unit tests
        run: npm test
        working-directory: todo-angular
