name: CI Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in root
        run: dir

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Lint Angular project
        run: ng lint

      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Build Angular project
        run: ng build --configuration production

      - name: List build files
        run: dir dist
